### ISSUE TITLE
About train data's path

### ISSUE THREAD

**Issue by Dadiziji** [junqiangchen/Unet_3d#1]
Thanks for your code and I have a problem.
In the "unet3dtest.py",the data is required in CSV format. How should I convert the image to CSV format?

**Comment by junqiangchen** [comment]
the image csv format like this:
D:\Data\LIDC\3DImage_Mask\Image/0_10_0
D:\Data\LIDC\3DImage_Mask\Image/0_11_0
D:\Data\LIDC\3DImage_Mask\Image/0_11_1
the mask csv format like this:
D:\Data\LIDC\3DImage_Mask\Image/0_10_0
D:\Data\LIDC\3DImage_Mask\Image/0_11_0
D:\Data\LIDC\3DImage_Mask\Image/0_11_1

every file folder contains three images
but pay attention to keep Image and Mask file folder Consistently
